### ISSUE TITLE
[Bug]: Beds made from patterns from the AdditionalBanners mod breaks the bed texture.

### ISSUE THREAD

**Issue by Mikzoru** [TheIllusiveC4/Bedspreads#22]
.

**Comment by TheIllusiveC4** [comment]
It seems you're using an outdated version of Bedspreads, which notably does not have integration with some Additional Banners textures. Please update to the latest Bedspreads version on 1.18.2 and re-test.

**Comment by Mikzoru** [comment]
I only just realized the mod had been updated since I first installed it and I noticed compatibility with Additional Banners has been added. I've tested with the new version and can confirm it now works. I'm sorry for the confusion. >.<
