### ISSUE TITLE
Compatibility with Comforts

### ISSUE THREAD

**Issue by QuartzSTQ** [TheIllusiveC4/Bedspreads#5]
I have no idea if this is intentional or not, but when I try to combine a Comforts sleeping bag with a banner, it creates a regular bed saying that it is decorated with the banner in the tooltip.

![Here's a GIF for a better demo.](https://user-images.githubusercontent.com/44265435/72177180-cf34e180-33e8-11ea-912b-a85dddc13f6a.gif)

**Comment by TheIllusiveC4** [comment]
Woah, that's definitely weird and not intended. I'll look into it.

**Comment by TheIllusiveC4** [comment]
This should be fixed on Comforts' end as of its 2.0-beta6 version.
